pipeline {
    agent {label 'python3'}
    stages{
        stage ('pull from vcs'){
            steps {
                git url: 'https://github.com/Qtalha/python-webcount.git',
                branch: 'python'
            }
        }
            stage('run tox'){
        steps{
            sh 'tox -e py'
        }
    }
    stage('test reports'){
        steps{
        junit 'junit-py.xml'
        }
    }
    }
}

