pipeline {
    agent {label 'python3'}
    stages{
        stage ('pull from vcs'){
            steps {
                git url : 'https://github.com/Qtalha/python-webcount.git'
                branch : 'python'
            }
            stage ('archive results'){
                steps { 
                    junit '/** junit-python39.xml'

                }
            }
            stage (artifacts){
                archiveArtifacts artifacts: '**/webcount-0.1.zip' 
            }

        }
    }
}
